/* LearnerGenie - profile-driven educational context. */
(function () {
    const REGIONS = {
        US: { countryCode:'US',countryName:'United States',currency:'USD',billingCurrency:'USD',locale:'en-US',levelLabel:'Grade',levelType:'grade',mathsConvention:'PEMDAS',englishStyle:'American English',terminology:'Use US school terminology: parentheses, exponents, slope, math, period, and grade-level language.',units:'Use US customary units when a US school context naturally calls for them, while remaining comfortable with metric units and preserving units supplied by the learner.',curriculumGuidance:'Use mainstream US grade-level expectations. For mathematics and English language arts/literacy, align broadly with Common Core where applicable. For science, social studies, and other subjects, use mainstream US grade-level conventions unless a specific state or curriculum standard is supplied.' },
        GB: { countryCode:'GB',countryName:'United Kingdom',currency:'GBP',billingCurrency:'USD',locale:'en-GB',levelLabel:'Year',levelType:'year',mathsConvention:'BODMAS',englishStyle:'British English',terminology:'Use UK school terminology and British English conventions: brackets, indices, gradient, maths, full stop, and Year-level language. Refer to school levels as Years rather than Grades.',units:'Use metric units and UK contextual examples where appropriate. Use pounds sterling for normal educational examples while preserving units and currencies supplied by the learner.',curriculumGuidance:'Use the learner’s selected UK curriculum and Year-level expectations. For England National Curriculum learners, align broadly with the appropriate Year and Key Stage. For Wales, Scotland or Northern Ireland, follow the selected national curriculum context rather than assuming the England National Curriculum.' },
        ZA: { countryCode:'ZA',countryName:'South Africa',currency:'ZAR',billingCurrency:'ZAR',locale:'en-ZA',levelLabel:'Grade',levelType:'grade',mathsConvention:'BODMAS',englishStyle:'South African/British English',terminology:'Use South African school terminology and British English conventions: brackets, indices, gradient, maths, full stop, and grade-level language.',units:'Use metric units and South African contextual examples where appropriate, while preserving units supplied by the learner.',curriculumGuidance:'Use South African grade-level expectations and the learner’s selected curriculum, including CAPS or IEB where specified.' }
    };
    let activeProfile=null,activeAccount=null,observer=null,ttsPatched=false,answerToolsPatched=false;
    function normaliseCountry(profile,account){const value=String(profile?.country_code||account?.country_code||account?.billing_region||'ZA').toUpperCase();return REGIONS[value]?value:'ZA';}
    function normaliseCurriculum(value,countryCode){const raw=String(value||'').trim();if(!raw){if(countryCode==='US')return 'US grade-level standards';if(countryCode==='GB')return 'England National Curriculum';return 'South African grade-level curriculum';}const labels={US_COMMON_CORE:'Common Core',US_STATE:'US state standards',US_HOMESCHOOL:'US homeschool curriculum',UK_ENGLAND_NC:'England National Curriculum',UK_WALES_CFW:'Curriculum for Wales',UK_SCOTLAND_CFE:'Curriculum for Excellence (Scotland)',UK_NI:'Northern Ireland Curriculum',ZA_CAPS:'CAPS',ZA_IEB:'IEB',CAPS:'CAPS',IEB:'IEB',CAMBRIDGE:'Cambridge / International',OTHER:'Other / specified curriculum'};return labels[raw]||raw.replace(/_/g,' ');}
    function normaliseLevel(value,countryCode){const raw=String(value||'').replace(/^grade\s*/i,'').replace(/^year\s*/i,'').trim();if(countryCode==='GB'&&/^(r|reception)$/i.test(raw))return 'Reception';return raw;}
    function inferEducationSystem(profile,countryCode){if(profile?.education_system)return String(profile.education_system);const curriculum=String(profile?.curriculum_code||'').toUpperCase();if(countryCode==='GB'){if(curriculum==='UK_SCOTLAND_CFE')return 'Scotland';if(curriculum==='UK_WALES_CFW')return 'Wales';if(curriculum==='UK_NI')return 'Northern Ireland';if(curriculum==='CAMBRIDGE')return 'UK / international education';return 'England';}return countryCode==='US'?'United States school system':'South African school system';}
    function getContext(profile=activeProfile,account=activeAccount){const countryCode=normaliseCountry(profile,account),base=REGIONS[countryCode];const mathsConvention=String(profile?.maths_convention||base.mathsConvention).toUpperCase()==='PEMDAS'?'PEMDAS':'BODMAS';const language=profile?.preferred_language||profile?.language||'English';const locale=language==='English'?base.locale:language==='Afrikaans'?'af-ZA':language==='Spanish'?'es-US':base.locale;const level=normaliseLevel(profile?.education_level??profile?.grade,countryCode);return {...base,countryCode,grade:level,level,curriculum:normaliseCurriculum(profile?.curriculum_code,countryCode),educationSystem:inferEducationSystem(profile,countryCode),mathsConvention,language,locale};}
    function buildPromptContext(profile=activeProfile,account=activeAccount){const c=getContext(profile,account);const levelLine=c.level?`${c.levelLabel}: ${c.level==='Reception'?'Reception':`${c.levelLabel} ${c.level}`}`:`${c.levelLabel}: Use the learner age/level evident from the request`;const languageInstruction=c.language==='English'?`Write learner-facing text in ${c.englishStyle}.`:`Write learner-facing explanations in ${c.language} by default unless the learner requests another language or the task is explicitly studying a different language. Preserve source quotations and required subject-language examples.`;return `\n\nAUTHORITATIVE LEARNER CONTEXT\nCountry: ${c.countryName}\n${levelLine}\nEducation system: ${c.educationSystem}\nCurriculum context: ${c.curriculum}\nMaths convention: ${c.mathsConvention}\nPreferred language: ${c.language}\nLocale: ${c.locale}\n\nRegional rules:\n- ${languageInstruction}\n- ${c.terminology}\n- ${c.units}\n- ${c.curriculumGuidance}\n- In arithmetic order-of-operations explanations, call the convention ${c.mathsConvention}.\n- Keep examples, school vocabulary, spelling and cultural references natural for ${c.countryName}, unless the learner's question or uploaded material clearly uses another context.\n- Use ${c.currency} for invented educational price examples unless the learner supplies a different currency. Billing currency is a separate commercial setting and must not influence learning examples.\n- Preserve facts, notation, names, quotations, source material, currencies and units supplied by the learner; localisation must not distort source content.\n- These learner-context rules override generic regional defaults or conflicting terminology elsewhere in the request.`;}
    function localiseVisibleCopy(){const c=getContext();document.querySelectorAll('.lg-field-note span').forEach(el=>{if(/UK\/South African terminology and BODMAS/i.test(el.textContent||'')){el.textContent=c.countryCode==='US'?'We use US school terminology and PEMDAS where appropriate.':c.countryCode==='GB'?'We use UK school terminology and BODMAS where appropriate.':'We use South African terminology and BODMAS where appropriate.';}});}
    function patchTTS(){if(ttsPatched||!window.LearnerOutput?.tts?.speak)return;const original=window.LearnerOutput.tts.speak.bind(window.LearnerOutput.tts);window.LearnerOutput.tts.speak=function(text,btnEl,lang){const c=getContext();const requested=String(lang||'');const effective=(!requested||requested.toLowerCase()==='en-za')?c.locale:requested;return original(text,btnEl,effective);};ttsPatched=true;}
    function patchAnswerTools(){if(answerToolsPatched||!window.LearnerGenieAnswerTools?.createOutputToolbar)return;const original=window.LearnerGenieAnswerTools.createOutputToolbar.bind(window.LearnerGenieAnswerTools);window.LearnerGenieAnswerTools.createOutputToolbar=function(options={}){const c=getContext();const defaultLanguage=(c.countryCode==='US'&&options.defaultLanguage==='af')?'es':options.defaultLanguage;return original({...options,defaultLanguage});};answerToolsPatched=true;}
    function setProfile(profile,account){activeProfile=profile||null;activeAccount=account||null;const context=getContext();document.documentElement.lang=context.locale;document.documentElement.dataset.learnerCountry=context.countryCode;document.documentElement.dataset.learnerLocale=context.locale;document.documentElement.dataset.mathsConvention=context.mathsConvention;document.documentElement.dataset.educationLevelType=context.levelType;patchTTS();patchAnswerTools();localiseVisibleCopy();if(!observer){observer=new MutationObserver(localiseVisibleCopy);observer.observe(document.body,{childList:true,subtree:true});}window.dispatchEvent(new CustomEvent('learner-region-changed',{detail:context}));return context;}
    function getRegion(){return getContext();}function getLocale(){return getContext().locale;}function getMathsConvention(){return getContext().mathsConvention;}
    window.LearnerRegion={setProfile,getRegion,getContext,getLocale,getMathsConvention,buildPromptContext};
})();