/* LearnerGenie role-aware onboarding. Requires learner-auth.js and region-config.js. */
(function(){
  const root=document.getElementById('ob-root');
  const client=window.LearnerAuth?.supabase;
  let session,account;
  const state={path:null,country:'US',name:'',grade:'5',curriculum:'US_COMMON_CORE',language:'English',educatorType:'private_tutor',workspaceType:'individual',organisationName:'',grades:['4','5','6'],subjects:['Math','English']};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const icon=()=>window.lucide?.createIcons();

  function setStep(step){
    const widths={1:12,2:42,3:72,4:100};
    document.getElementById('ob-fill').style.width=`${widths[step]||12}%`;
    document.getElementById('ob-progress-text').textContent=`${step} of 4`;
    document.getElementById('ob-stage').textContent=step===1?'Getting started':step===2?'Set up your context':step===3?'Confirm access':'Ready to go';
    document.querySelectorAll('.ob-step').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.step)===step));
  }
  function render(html,step){root.innerHTML=`<section class="ob-card">${html}</section>`;setStep(step);icon();window.scrollTo({top:0,behavior:'smooth'});}
  function error(message){const old=root.querySelector('.ob-error');if(old)old.remove();root.querySelector('.ob-card')?.insertAdjacentHTML('beforeend',`<div class="ob-error">${esc(message)}</div>`);}
  function loading(button,label='Saving…'){button.disabled=true;button.dataset.old=button.innerHTML;button.textContent=label;}
  function restore(button){button.disabled=false;if(button.dataset.old)button.innerHTML=button.dataset.old;icon();}
  function backButton(target){return `<button class="ob-btn ob-btn-ghost" data-go="${target}">Back</button>`;}
  function bindGo(){root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>screens[b.dataset.go]());}

  const screens={};
  screens.role=function(){
    render(`<div class="ob-eyebrow">Welcome to LearnerGenie</div><h2>How would you like to use LearnerGenie first?</h2><p class="ob-sub">You can add another workspace later. This just helps us set up the right experience now.</p><div class="ob-choices"><button class="ob-choice" id="family-choice"><div class="ob-choice-icon is-family"><i data-lucide="heart-handshake"></i></div><h3>Support my child</h3><p>Create learner profiles and give your child guided support for homework, revision, maths and practice.</p><small>Family & learner access →</small></button><button class="ob-choice" id="educator-choice"><div class="ob-choice-icon is-edu"><i data-lucide="graduation-cap"></i></div><h3>Tutor or teach learners</h3><p>Organise learners, create groups and follow their learning activity from a free educator dashboard.</p><small>Tutor & teacher access is free →</small></button></div>`,1);
    document.getElementById('family-choice').onclick=()=>{state.path='family';screens.familyCountry();};
    document.getElementById('educator-choice').onclick=()=>{state.path='educator';screens.educatorType();};
  };
  screens.familyCountry=function(){
    render(`<div class="ob-eyebrow">Family onboarding · Step 1</div><h2>Where will your learner use LearnerGenie?</h2><p class="ob-sub">We use this to set the right curriculum, language and pricing. You can change it later.</p><div class="ob-field"><label>Country or region</label><select id="country"><option value="US" ${state.country==='US'?'selected':''}>United States</option><option value="ZA" ${state.country==='ZA'?'selected':''}>South Africa</option></select></div><div class="ob-actions">${backButton('role')}<button class="ob-btn ob-btn-primary" id="country-next">Continue <i data-lucide="arrow-right"></i></button></div>`,2);bindGo();
    document.getElementById('country-next').onclick=()=>{state.country=document.getElementById('country').value;const r=window.LearnerRegions.byCode(state.country);state.curriculum=r.curricula[0][0];screens.familyLearner();};
  };
  screens.familyLearner=function(){
    const r=window.LearnerRegions.byCode(state.country);const grades=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${String(i+1)===String(state.grade)?'selected':''}>Grade ${i+1}</option>`).join('');const curricula=r.curricula.map(([v,l])=>`<option value="${esc(v)}" ${v===state.curriculum?'selected':''}>${esc(l)}</option>`).join('');
    render(`<div class="ob-eyebrow">Family onboarding · Step 2</div><h2>Tell us about your learner.</h2><p class="ob-sub">Only the information LearnerGenie needs to tailor the learning experience.</p><div class="ob-grid"><div class="ob-field"><label>First name</label><input id="learner-name" value="${esc(state.name)}" placeholder="First name"></div><div class="ob-field"><label>Grade</label><select id="grade">${grades}</select></div><div class="ob-field"><label>Curriculum</label><select id="curriculum">${curricula}</select></div><div class="ob-field"><label>Preferred language</label><select id="language"><option>English</option><option>Spanish</option><option>Afrikaans</option></select></div></div><div class="ob-actions">${backButton('familyCountry')}<button class="ob-btn ob-btn-primary" id="learner-next">Continue <i data-lucide="arrow-right"></i></button></div>`,2);bindGo();
    document.getElementById('learner-next').onclick=()=>{const name=document.getElementById('learner-name').value.trim();if(!name)return error('Please enter your learner’s first name.');state.name=name;state.grade=document.getElementById('grade').value;state.curriculum=document.getElementById('curriculum').value;state.language=document.getElementById('language').value;screens.familyAccess();};
  };
  screens.familyAccess=function(){
    const r=window.LearnerRegions.byCode(state.country);let plans='';if(r.pricing){plans=`<div class="ob-plans"><div class="ob-plan"><span class="ob-badge">1 learner</span><h3>Learner</h3><div class="ob-price">$${r.pricing.one.toFixed(2)} <span>/ month</span></div><p>Full access for one learner.</p></div><div class="ob-plan is-featured"><span class="ob-badge">Family</span><h3>Up to 2 learners</h3><div class="ob-price">$${r.pricing.two.toFixed(2)} <span>/ month</span></div><p>Full access for two learner profiles.</p></div><div class="ob-plan"><span class="ob-badge">Family Plus</span><h3>Up to 4 learners</h3><div class="ob-price">$${r.pricing.four.toFixed(2)} <span>/ month</span></div><p>Full access for larger households.</p></div></div>`;}
    render(`<div class="ob-eyebrow">Family onboarding · Step 3</div><h2>Start free. Upgrade when it becomes useful.</h2><p class="ob-sub">${esc(state.name)} can start with ${r.freeWeeklyActivities} learning activities every week. No payment is required to begin.</p><div class="ob-freebox"><div class="ob-choice-icon" style="background:#fff0bd;color:#9a6900;margin:0"><i data-lucide="sparkles"></i></div><div><strong>Free learner access</strong><br><span style="color:var(--muted);font-size:14px">${r.freeWeeklyActivities} learning activities every week.</span></div></div>${plans}<div class="ob-actions">${backButton('familyLearner')}<button class="ob-btn ob-btn-secondary" id="complete-family">Continue with free access</button></div>`,3);bindGo();document.getElementById('complete-family').onclick=completeFamily;
  };
  screens.familyDone=function(profileId){render(`<div class="ob-success"><i data-lucide="check-circle-2"></i></div><div class="ob-eyebrow" style="margin-top:18px">Ready to learn</div><h2>${esc(state.name)} is ready.</h2><p class="ob-sub">Their learner profile has been created with free weekly access.</p><div class="ob-actions"><a class="ob-btn ob-btn-secondary" href="/onboarding.html?mode=family&add=1">Add another learner</a><a class="ob-btn ob-btn-primary" href="/app.html?profile_id=${encodeURIComponent(profileId)}">Start learning <i data-lucide="arrow-right"></i></a></div>`,4);};

  screens.educatorType=function(){
    const types=[['private_tutor','Private tutor'],['teacher','Teacher'],['homeschool','Homeschool educator'],['tutor_centre','Tutor centre'],['school','School / learning organisation'],['other','Other']];
    render(`<div class="ob-eyebrow">Educator onboarding · Step 1</div><h2>What best describes you?</h2><p class="ob-sub">This helps us tailor the workspace. Tutor and teacher dashboard access remains free.</p><div class="ob-pills" id="type-pills">${types.map(([v,l])=>`<button class="ob-pill ${state.educatorType===v?'is-active':''}" data-value="${v}">${l}</button>`).join('')}</div><div class="ob-actions">${backButton('role')}<button class="ob-btn ob-btn-primary" id="type-next">Continue <i data-lucide="arrow-right"></i></button></div>`,1);bindGo();root.querySelectorAll('#type-pills .ob-pill').forEach(p=>p.onclick=()=>{state.educatorType=p.dataset.value;root.querySelectorAll('#type-pills .ob-pill').forEach(x=>x.classList.toggle('is-active',x===p));});document.getElementById('type-next').onclick=()=>{if(['tutor_centre','school'].includes(state.educatorType))state.workspaceType='organisation';screens.educatorWork();};
  };
  screens.educatorWork=function(){
    render(`<div class="ob-eyebrow">Educator onboarding · Step 2</div><h2>How do you work?</h2><p class="ob-sub">Independent tutors get their own workspace. Centres and schools get an organisation workspace.</p><div class="ob-choices"><button class="ob-choice ${state.workspaceType==='individual'?'is-selected':''}" data-work="individual"><div class="ob-choice-icon is-edu"><i data-lucide="user"></i></div><h3>Just me</h3><p>Create an individual tutor workspace that only you manage.</p><small>Free educator workspace</small></button><button class="ob-choice ${state.workspaceType==='organisation'?'is-selected':''}" data-work="organisation"><div class="ob-choice-icon is-edu"><i data-lucide="building-2"></i></div><h3>Organisation / centre / school</h3><p>Create a shared workspace that can later include staff and administrators.</p><small>Organisation workspace</small></button></div><div class="ob-field ${state.workspaceType==='organisation'?'':'ob-hidden'}" id="org-wrap" style="margin-top:18px"><label>Organisation name</label><input id="org-name" value="${esc(state.organisationName)}" placeholder="Organisation name"></div><div class="ob-actions">${backButton('educatorType')}<button class="ob-btn ob-btn-primary" id="work-next">Continue <i data-lucide="arrow-right"></i></button></div>`,2);bindGo();root.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{state.workspaceType=b.dataset.work;root.querySelectorAll('[data-work]').forEach(x=>x.classList.toggle('is-selected',x===b));document.getElementById('org-wrap').classList.toggle('ob-hidden',state.workspaceType!=='organisation');});document.getElementById('work-next').onclick=()=>{if(state.workspaceType==='organisation'){state.organisationName=document.getElementById('org-name').value.trim();if(!state.organisationName)return error('Please enter the organisation or centre name.');}screens.educatorContext();};
  };
  screens.educatorContext=function(){
    const gradeButtons=Array.from({length:12},(_,i)=>{const v=String(i+1);return `<button class="ob-pill ${state.grades.includes(v)?'is-active':''}" data-grade="${v}">Grade ${v}</button>`}).join('');const subjects=['Math','English','Science','History','Other'];
    render(`<div class="ob-eyebrow">Educator onboarding · Step 3</div><h2>Tell us about the learners you support.</h2><p class="ob-sub">These settings help make filters, reporting and invitations more relevant.</p><div class="ob-grid"><div class="ob-field"><label>Country</label><select id="edu-country"><option value="US" ${state.country==='US'?'selected':''}>United States</option><option value="ZA" ${state.country==='ZA'?'selected':''}>South Africa</option></select></div><div class="ob-field"><label>Main curriculum</label><select id="edu-curriculum"><option value="US_COMMON_CORE">Common Core</option><option value="US_STATE">State standards</option><option value="MIXED">Mixed / multiple curricula</option><option value="OTHER">Other</option></select></div><div class="ob-field ob-full"><label>Grades you work with</label><div class="ob-pills" id="grade-pills">${gradeButtons}</div></div><div class="ob-field ob-full"><label>Subjects</label><div class="ob-pills" id="subject-pills">${subjects.map(v=>`<button class="ob-pill ${state.subjects.includes(v)?'is-active':''}" data-subject="${v}">${v}</button>`).join('')}</div></div></div><div class="ob-actions">${backButton('educatorWork')}<button class="ob-btn ob-btn-primary" id="context-next">Continue <i data-lucide="arrow-right"></i></button></div>`,3);bindGo();root.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{const v=b.dataset.grade;state.grades=state.grades.includes(v)?state.grades.filter(x=>x!==v):[...state.grades,v];b.classList.toggle('is-active');});root.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{const v=b.dataset.subject;state.subjects=state.subjects.includes(v)?state.subjects.filter(x=>x!==v):[...state.subjects,v];b.classList.toggle('is-active');});document.getElementById('context-next').onclick=()=>{state.country=document.getElementById('edu-country').value;state.curriculum=document.getElementById('edu-curriculum').value;screens.educatorAdd();};
  };
  screens.educatorAdd=function(){render(`<div class="ob-eyebrow">Educator onboarding · Step 4</div><h2>How would you like to add learners?</h2><p class="ob-sub">You don't need to have learner details ready now. Enter the dashboard first and invite people when you're ready.</p><div class="ob-choices"><div class="ob-choice"><div class="ob-choice-icon is-edu"><i data-lucide="mail-plus"></i></div><h3>Invite learners or parents</h3><p>Connect existing learner profiles without changing ownership.</p><small>Available from your dashboard</small></div><div class="ob-choice"><div class="ob-choice-icon is-family"><i data-lucide="user-plus"></i></div><h3>Create a learner profile</h3><p>Useful when the tutor or organisation handles learner setup.</p><small>Learner access stays separate</small></div></div><div class="ob-info"><strong>Important:</strong> free tutor access does not grant premium learner access. Each learner remains Free or Premium according to their own entitlement.</div><div class="ob-actions">${backButton('educatorContext')}<button class="ob-btn ob-btn-secondary" id="complete-educator">Create my free workspace</button></div>`,3);bindGo();document.getElementById('complete-educator').onclick=completeEducator;};
  screens.educatorDone=function(){render(`<div class="ob-success"><i data-lucide="badge-check"></i></div><div class="ob-eyebrow" style="margin-top:18px">Tutor workspace ready</div><h2>Your educator dashboard is ready.</h2><p class="ob-sub">Your tutor workspace is free. Learner profiles and learner subscriptions remain separate.</p><div class="ob-actions"><a class="ob-btn ob-btn-secondary" href="/onboarding.html?mode=family&add=1">Add a learner for my family</a><a class="ob-btn ob-btn-primary" href="/tutor-dashboard-v2.html">Open tutor dashboard <i data-lucide="arrow-right"></i></a></div>`,4);};

  async function completeFamily(e){const btn=e.currentTarget;loading(btn);try{const r=window.LearnerRegions.byCode(state.country);const {data,error:rpcError}=await client.rpc('complete_family_onboarding',{p_name:state.name,p_grade:`Grade ${state.grade}`,p_language:state.language,p_country_code:state.country,p_curriculum_code:state.curriculum,p_education_system:state.curriculum,p_maths_convention:r.mathsConvention});if(rpcError)throw rpcError;const profileId=(typeof data==='object'&&data?.profile_id)||data;if(!profileId)throw new Error('Learner profile was created but no profile ID was returned.');screens.familyDone(profileId);}catch(err){restore(btn);error(`We couldn't finish learner setup: ${err.message}`);}}
  async function completeEducator(e){const btn=e.currentTarget;loading(btn);try{const workspaceName=state.workspaceType==='organisation'?state.organisationName:`${session.user.email?.split('@')[0]||'My'} Tutor Workspace`;const {error:rpcError}=await client.rpc('complete_educator_onboarding',{p_workspace_name:workspaceName,p_workspace_type:state.workspaceType,p_educator_type:state.educatorType,p_country_code:state.country,p_curriculum_code:state.curriculum,p_grades:state.grades,p_subjects:state.subjects});if(rpcError)throw rpcError;screens.educatorDone();}catch(err){restore(btn);error(`We couldn't create the tutor workspace: ${err.message}`);}}

  async function routeExisting(profiles,memberships){const last=account?.last_workspace_type;if(last==='educator'&&memberships.length)return location.replace('/tutor-dashboard-v2.html');if(profiles.length)return location.replace('/app.html');if(memberships.length)return location.replace('/tutor-dashboard-v2.html');}
  async function init(){
    if(!client)return root.innerHTML='<div class="ob-error">LearnerGenie could not connect to authentication.</div>';
    session=await window.LearnerAuth.requireSession();if(!session)return;
    account=await window.LearnerAuth.getAccount(session.user.id);
    const [{data:profiles,error:pError},{data:memberships,error:mError}]=await Promise.all([client.from('profiles').select('id').eq('account_id',session.user.id).limit(1),client.from('tutor_centre_users').select('tutor_centre_id,status').eq('account_id',session.user.id).eq('status','active').limit(1)]);
    if(pError)console.warn(pError);if(mError)console.warn(mError);
    const params=new URLSearchParams(location.search);const forced=params.get('mode');const add=params.get('add')==='1';
    if(!forced&&!add&&((profiles||[]).length||(memberships||[]).length)){try{await client.from('accounts').update({onboarding_completed:true,onboarding_completed_at:new Date().toISOString()}).eq('id',session.user.id);}catch{}return routeExisting(profiles||[],memberships||[]);}
    state.country=window.LearnerRegions.inferred().countryCode;
    if(forced==='family'){state.path='family';return screens.familyCountry();}
    if(forced==='educator'){state.path='educator';return screens.educatorType();}
    screens.role();
  }
  init();
})();
