/* LearnerGenie unified upgrade flow. */
(function(){
  const root=document.getElementById('upgrade-plans');
  const message=document.getElementById('upgrade-message');
  const client=window.LearnerAuth?.supabase;
  let session=null,account=null,profile=null;
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  function show(text,type='error'){message.innerHTML=`<div class="message ${type}">${esc(text)}</div>`;}
  function region(){const value=String(account?.billing_region||account?.country_code||profile?.country_code||'ZA').toUpperCase();return value==='US'?'US':'ZA';}
  function plans(){return region()==='US'?[{key:'single',label:'Single Learner',badge:'1 learner',price:'$5.99',copy:'Unlimited access for one learner profile.'},{key:'two',label:'Family',badge:'Up to 2 learners',price:'$7.99',copy:'Unlimited access for two learner profiles.',featured:true},{key:'four',label:'Family Plus',badge:'Up to 4 learners',price:'$10.99',copy:'Unlimited access for up to four learner profiles.'}]:[{key:'paid_single',label:'Learner',badge:'1 learner',price:'R69',copy:'Unlimited access for one learner profile.'},{key:'paid_family',label:'Family',badge:'Up to 2 learners',price:'R99',copy:'Unlimited access for two learner profiles.',featured:true},{key:'paid_ultra',label:'Family Plus',badge:'Up to 4 learners',price:'R149',copy:'Unlimited access for up to four learner profiles.'}];}
  function render(){root.innerHTML=plans().map(p=>`<article class="plan${p.featured?' featured':''}"><span class="badge">${esc(p.badge)}</span><h2>${esc(p.label)}</h2><div class="price">${esc(p.price)} <span>/ month</span></div><p>${esc(p.copy)}</p><button class="choose" data-plan="${esc(p.key)}">Choose ${esc(p.label)}</button></article>`).join('');root.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>start(b.dataset.plan,b));window.lucide?.createIcons();}
  async function start(plan,button){message.innerHTML='';button.disabled=true;const old=button.textContent;button.textContent='Opening secure checkout…';try{if(region()==='US'){location.href=`/us-subscribe.html?plan=${encodeURIComponent(plan)}`;return;}const res=await fetch('/.netlify/functions/create-subscription',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.access_token}`},body:JSON.stringify({plan})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'Could not start checkout.');if(!body.checkoutUrl)throw new Error('Checkout URL was not returned.');location.href=body.checkoutUrl;}catch(err){show(err.message||'Could not start checkout.');button.disabled=false;button.textContent=old;}}
  async function init(){if(!client){show('LearnerGenie could not connect to your account.');return;}session=await window.LearnerAuth.requireSession();if(!session)return;account=await window.LearnerAuth.getAccount(session.user.id);if(String(account?.active_tier||'free').toLowerCase()!=='free'||['active','paid','trialing','past_due'].includes(String(account?.subscription_status||'').toLowerCase())){show('This account already has a subscription. A second subscription cannot be started here.','info');return;}const requested=window.LearnerAuth.getProfileIdFromUrl();if(requested){const {data}=await client.from('profiles').select('id,country_code').eq('id',requested).eq('account_id',session.user.id).maybeSingle();profile=data||null;}document.getElementById('upgrade-copy').textContent=region()==='US'?'Choose the number of learner profiles your family needs. Paid plans include unlimited learning activities, full history and Study Squads.':'Choose the number of learner profiles your family needs. Paid plans include unlimited learning activities, full history and Study Squads.';render();}
  init();
})();